# Generated by Django 3.2.12 on 2022-04-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataRequesterPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('data_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.datarequester')),
            ],
        ),
        migrations.CreateModel(
            name='RequesterOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='organization', max_length=1024)),
                ('data_requester_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.datarequesterpersonal')),
            ],
        ),
        migrations.CreateModel(
            name='RequesterOrganizationBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('requester_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.requesterorganization')),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_file', models.FilePathField()),
                ('commentary_to_file', models.TextField(null=True)),
                ('type_data', models.CharField(choices=[('retr', 'Retro data'), ('real', 'IP address')], max_length=4)),
                ('basis', models.TextField(null=True)),
                ('data_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.datarequester')),
            ],
        ),
        migrations.CreateModel(
            name='DataRequesterPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('data_requester_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.datarequesterpersonal')),
            ],
        ),
    ]
