# Generated by Django 3.2.12 on 2022-04-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequesterpersonal',
            name='data_requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqester', to='gsras.datarequester'),
        ),
        migrations.AlterField(
            model_name='datarequesterphone',
            name='data_requester_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_hone', to='gsras.datarequesterpersonal'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='data_requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='gsras.datarequester'),
        ),
    ]
