# Generated by Django 3.2.12 on 2022-04-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsras', '0003_auto_20220415_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='data_requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.datarequester'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='type_data',
            field=models.CharField(max_length=200),
        ),
    ]
