# Generated by Django 3.2.12 on 2022-04-25 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsras', '0004_auto_20220415_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
