# Generated by Django 3.2.12 on 2022-05-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsras', '0005_requestdata_date_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField()),
                ('position', models.CharField(max_length=512)),
                ('href', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_storage', models.URLField(null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.news')),
            ],
        ),
    ]
