# Generated by Django 3.2.12 on 2022-05-16 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsras', '0006_news_newsimagecontent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsimagecontent',
            name='image_storage',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='NewsAttachmentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.TextField(null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsras.news')),
            ],
        ),
    ]
