# Generated by Django 3.2.12 on 2022-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsras', '0007_auto_20220516_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
