# Generated by Django 3.2.12 on 2022-05-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsras', '0009_alter_newsimagecontent_image_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMapPointFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Добавить координаты события',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новостная лента'},
        ),
        migrations.AlterModelOptions(
            name='newsimagecontent',
            options={'verbose_name_plural': 'Добавить изображение'},
        ),
        migrations.DeleteModel(
            name='NewsAttachmentContent',
        ),
        migrations.AddField(
            model_name='newsmappointfloat',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gsras.news'),
        ),
    ]
